
Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1

Python 3.5.4
../PreprocessedData/preprocessedForCNN/299 x 299 n/imgData_(299, 299, 3)_test.npy
../PreprocessedData/preprocessedForCNN/299 x 299 n/targetData_(299, 299, 3)_test.csv
../modelOutput/compareModels4/ResNet50_2019-06-14_15_8_default_299/ResNet50.hdf5
_testSet_
2019-06-14 23:23:52.290100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:83:00.0
totalMemory: 11.91GiB freeMemory: 11.63GiB
2019-06-14 23:23:52.290271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-14 23:23:52.645401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-14 23:23:52.645553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-14 23:23:52.645596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-14 23:23:52.645947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11251 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:83:00.0, compute capability: 6.0)
2019-06-14 23:23:52.646395: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
trn path: ../PreprocessedData/preprocessedForCNN/299 x 299 n/imgData_(299, 299, 3)_test.npy

 32/968 [..............................] - ETA: 1:42
 64/968 [>.............................] - ETA: 52s 
 96/968 [=>............................] - ETA: 35s
128/968 [==>...........................] - ETA: 26s
160/968 [===>..........................] - ETA: 21s
192/968 [====>.........................] - ETA: 18s
224/968 [=====>........................] - ETA: 15s
256/968 [======>.......................] - ETA: 13s
288/968 [=======>......................] - ETA: 12s
320/968 [========>.....................] - ETA: 10s
352/968 [=========>....................] - ETA: 9s 
384/968 [==========>...................] - ETA: 8s
416/968 [===========>..................] - ETA: 7s
448/968 [============>.................] - ETA: 7s
480/968 [=============>................] - ETA: 6s
512/968 [==============>...............] - ETA: 5s
544/968 [===============>..............] - ETA: 5s
576/968 [================>.............] - ETA: 4s
608/968 [=================>............] - ETA: 4s
640/968 [==================>...........] - ETA: 3s
672/968 [===================>..........] - ETA: 3s
704/968 [====================>.........] - ETA: 2s
736/968 [=====================>........] - ETA: 2s
768/968 [======================>.......] - ETA: 2s
800/968 [=======================>......] - ETA: 1s
832/968 [========================>.....] - ETA: 1s
864/968 [=========================>....] - ETA: 1s
896/968 [==========================>...] - ETA: 0s
928/968 [===========================>..] - ETA: 0s
960/968 [============================>.] - ETA: 0s
968/968 [==============================] - 10s 10ms/step
Using TensorFlow backend.
	 accuracy: 0.907

	 binary (urgent vs non-urgent)
	 accuracy: 0.944
	 sensitivity 0.952
	 specificity 0.936
	 positive likelihood ratio 14.9
	 negative likelihood ratio 0.0508
Done!
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2b1b0976cac8>>
Traceback (most recent call last):
  File "/home/amourav/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable
