
Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1

Python 3.5.4
../PreprocessedData/preprocessedForCNN/299x299/imgData_(299, 299, 3)_train_n1000.npy
../PreprocessedData/preprocessedForCNN/299x299/targetData_(299, 299, 3)_train.npy
../modelOutput/compareModels2/Xception_dataAug_False2019-06-02_10_52_default/Xception.hdf5
_trainSet_
2019-06-09 20:09:52.569017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:83:00.0
totalMemory: 11.91GiB freeMemory: 11.63GiB
2019-06-09 20:09:52.569178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-09 20:09:52.940393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-09 20:09:52.940545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-09 20:09:52.940591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-09 20:09:52.940951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11251 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:83:00.0, compute capability: 6.0)
2019-06-09 20:09:52.941520: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
trn path: ../PreprocessedData/preprocessedForCNN/299x299/imgData_(299, 299, 3)_train_n1000.npy

  32/1000 [..............................] - ETA: 1:35
  64/1000 [>.............................] - ETA: 49s 
  96/1000 [=>............................] - ETA: 33s
 128/1000 [==>...........................] - ETA: 26s
 160/1000 [===>..........................] - ETA: 21s
 192/1000 [====>.........................] - ETA: 18s
 224/1000 [=====>........................] - ETA: 15s
 256/1000 [======>.......................] - ETA: 13s
 288/1000 [=======>......................] - ETA: 12s
 320/1000 [========>.....................] - ETA: 11s
 352/1000 [=========>....................] - ETA: 10s
 384/1000 [==========>...................] - ETA: 9s 
 416/1000 [===========>..................] - ETA: 8s
 448/1000 [============>.................] - ETA: 7s
 480/1000 [=============>................] - ETA: 6s
 512/1000 [==============>...............] - ETA: 6s
 544/1000 [===============>..............] - ETA: 5s
 576/1000 [================>.............] - ETA: 5s
 608/1000 [=================>............] - ETA: 4s
 640/1000 [==================>...........] - ETA: 4s
 672/1000 [===================>..........] - ETA: 3s
 704/1000 [====================>.........] - ETA: 3s
 736/1000 [=====================>........] - ETA: 2s
 768/1000 [======================>.......] - ETA: 2s
 800/1000 [=======================>......] - ETA: 2s
 832/1000 [=======================>......] - ETA: 1s
 864/1000 [========================>.....] - ETA: 1s
 896/1000 [=========================>....] - ETA: 1s
 928/1000 [==========================>...] - ETA: 0s
 960/1000 [===========================>..] - ETA: 0s
 992/1000 [============================>.] - ETA: 0s
1000/1000 [==============================] - 10s 10ms/step
Using TensorFlow backend.
Traceback (most recent call last):
  File "./modelPred.py", line 136, in <module>
    args.note)
  File "./modelPred.py", line 95, in main_driver
    modelPredDF = pd.DataFrame(index=yTest.index)
AttributeError: 'numpy.ndarray' object has no attribute 'index'
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2b122fcc5f98>>
Traceback (most recent call last):
  File "/home/amourav/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable
